# Generated by Django 4.0.4 on 2024-02-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('recever', models.CharField(max_length=30)),
                ('chat', models.TextField()),
                ('Date_time', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('recever', models.CharField(max_length=30)),
                ('chat', models.TextField(null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('Date_time', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=None, null=True)),
                ('growth', models.IntegerField(default=None, null=True)),
                ('expences', models.IntegerField(default=None, null=True)),
                ('profit', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField(default=None, null=True)),
                ('intensity', models.IntegerField(default=None, null=True)),
                ('sector', models.CharField(default=None, max_length=20, null=True)),
                ('topic', models.CharField(default=None, max_length=20, null=True)),
                ('insight', models.CharField(default=None, max_length=250, null=True)),
                ('url', models.CharField(default=None, max_length=250, null=True)),
                ('region', models.CharField(default=None, max_length=50, null=True)),
                ('start_year', models.IntegerField(default=None, null=True)),
                ('impact', models.IntegerField(default=None, null=True)),
                ('added', models.DateTimeField(default=None, null=True)),
                ('published', models.DateTimeField(default=None, null=True)),
                ('country', models.CharField(default=None, max_length=100, null=True)),
                ('relevance', models.IntegerField(default=None, null=True)),
                ('pestle', models.CharField(default=None, max_length=50, null=True)),
                ('source', models.CharField(default=None, max_length=50, null=True)),
                ('title', models.CharField(default=None, max_length=250, null=True)),
                ('likelihood', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_types', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('confirm_password', models.CharField(max_length=255)),
            ],
        ),
    ]
